name: SpeedRoute
options:
  bundleIdPrefix: com.example
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.28.0
targets:
  SpeedRoute:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - SpeedRoute
    settings:
      base:
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_USER_SCRIPT_SANDBOXING: NO
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseAnalytics
